services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_DB: ${DB_NAME}
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/lib/mssql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull:
    image: ollama/ollama
    depends_on:
      - ollama
    entrypoint: >
      sh -c "sleep 5 && ollama pull llama3.2"
    environment:
      OLLAMA_HOST: http://ollama:11434

volumes:
  sqldata:
  ollama_data:
